let myFirstName = "Dhiaa";
let myLastName = "Shalabi";
let myFullName = myFirstName + " " + myLastName;
let myHobbies = ["eat", "coding", "game"];
let currentStudent = true;
let myDream = "to be a good developer";
let bestFriend = "Ahmad";
let phoneNumber = "00000000";
let favoriteMeal = "Kunafa";
let myBirthYear = 1997;
let currentYear = 2023;
let myAge = currentYear - myBirthYear;
console.log("My First Name: ", myFirstName);
console.log("My Last Name: ", myLastName);
console.log("My Full Name: ", myFullName);
console.log("My Hobbies: ", myHobbies);
console.log("I am a student: ", currentStudent);
console.log("My Dream: ", myDream);
console.log("My Best Friend: ", bestFriend);
console.log("My Phone Number: ", phoneNumber);
console.log("My Favorite Meal: ", favoriteMeal);
console.log("My Birth Year: ", myBirthYear);
console.log("Current Year: ", currentYear);
console.log("My Age: ", myAge);
